# Generated by Django 5.1.2 on 2024-10-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('medical_history', models.TextField(blank=True)),
                ('surgical_history', models.TextField(blank=True)),
                ('social_history', models.TextField(blank=True)),
                ('presenting_illness', models.TextField(blank=True)),
            ],
        ),
    ]
