# Generated by Django 5.1.2 on 2024-10-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0004_alter_assessment_patient_alter_patient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medications',
            name='frequency',
            field=models.CharField(max_length=100),
        ),
    ]
